// Code generated by entc, DO NOT EDIT.

package thought

const (
	// Label holds the string label denoting the thought type in the database.
	Label = "thought"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldImageURL holds the string denoting the imageurl field in the database.
	FieldImageURL = "image_url"
	// FieldUserId holds the string denoting the userid field in the database.
	FieldUserId = "user_id"
	// Table holds the table name of the thought in the database.
	Table = "thoughts"
)

// Columns holds all SQL columns for thought fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldBody,
	FieldImageURL,
	FieldUserId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultBody holds the default value on creation for the "body" field.
	DefaultBody string
	// BodyValidator is a validator for the "body" field. It is called by the builders before save.
	BodyValidator func(string) error
)
