// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/d-exclaimation/fx-graphql-kit/ent/migrate"

	"github.com/d-exclaimation/fx-graphql-kit/ent/thought"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Thought is the client for interacting with the Thought builders.
	Thought *ThoughtClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Thought = NewThoughtClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Thought: NewThoughtClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:  cfg,
		Thought: NewThoughtClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Thought.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Thought.Use(hooks...)
}

// ThoughtClient is a client for the Thought schema.
type ThoughtClient struct {
	config
}

// NewThoughtClient returns a client for the Thought from the given config.
func NewThoughtClient(c config) *ThoughtClient {
	return &ThoughtClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `thought.Hooks(f(g(h())))`.
func (c *ThoughtClient) Use(hooks ...Hook) {
	c.hooks.Thought = append(c.hooks.Thought, hooks...)
}

// Create returns a create builder for Thought.
func (c *ThoughtClient) Create() *ThoughtCreate {
	mutation := newThoughtMutation(c.config, OpCreate)
	return &ThoughtCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Thought entities.
func (c *ThoughtClient) CreateBulk(builders ...*ThoughtCreate) *ThoughtCreateBulk {
	return &ThoughtCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Thought.
func (c *ThoughtClient) Update() *ThoughtUpdate {
	mutation := newThoughtMutation(c.config, OpUpdate)
	return &ThoughtUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ThoughtClient) UpdateOne(t *Thought) *ThoughtUpdateOne {
	mutation := newThoughtMutation(c.config, OpUpdateOne, withThought(t))
	return &ThoughtUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ThoughtClient) UpdateOneID(id int) *ThoughtUpdateOne {
	mutation := newThoughtMutation(c.config, OpUpdateOne, withThoughtID(id))
	return &ThoughtUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Thought.
func (c *ThoughtClient) Delete() *ThoughtDelete {
	mutation := newThoughtMutation(c.config, OpDelete)
	return &ThoughtDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ThoughtClient) DeleteOne(t *Thought) *ThoughtDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ThoughtClient) DeleteOneID(id int) *ThoughtDeleteOne {
	builder := c.Delete().Where(thought.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ThoughtDeleteOne{builder}
}

// Query returns a query builder for Thought.
func (c *ThoughtClient) Query() *ThoughtQuery {
	return &ThoughtQuery{config: c.config}
}

// Get returns a Thought entity by its id.
func (c *ThoughtClient) Get(ctx context.Context, id int) (*Thought, error) {
	return c.Query().Where(thought.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ThoughtClient) GetX(ctx context.Context, id int) *Thought {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ThoughtClient) Hooks() []Hook {
	return c.hooks.Thought
}
