// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"

	"github.com/d-exclaimation/fx-graphql-kit/ent/predicate"
	"github.com/d-exclaimation/fx-graphql-kit/ent/thought"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeThought = "Thought"
)

// ThoughtMutation represents an operation that mutates the Thought nodes in the graph.
type ThoughtMutation struct {
	config
	op            Op
	typ           string
	id            *int
	title         *string
	body          *string
	imageURL      *string
	userId        *int64
	adduserId     *int64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Thought, error)
	predicates    []predicate.Thought
}

var _ ent.Mutation = (*ThoughtMutation)(nil)

// thoughtOption allows management of the mutation configuration using functional options.
type thoughtOption func(*ThoughtMutation)

// newThoughtMutation creates new mutation for the Thought entity.
func newThoughtMutation(c config, op Op, opts ...thoughtOption) *ThoughtMutation {
	m := &ThoughtMutation{
		config:        c,
		op:            op,
		typ:           TypeThought,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withThoughtID sets the ID field of the mutation.
func withThoughtID(id int) thoughtOption {
	return func(m *ThoughtMutation) {
		var (
			err   error
			once  sync.Once
			value *Thought
		)
		m.oldValue = func(ctx context.Context) (*Thought, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Thought.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withThought sets the old Thought of the mutation.
func withThought(node *Thought) thoughtOption {
	return func(m *ThoughtMutation) {
		m.oldValue = func(context.Context) (*Thought, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ThoughtMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ThoughtMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID
// is only available if it was provided to the builder.
func (m *ThoughtMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetTitle sets the "title" field.
func (m *ThoughtMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *ThoughtMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Thought entity.
// If the Thought object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ThoughtMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *ThoughtMutation) ResetTitle() {
	m.title = nil
}

// SetBody sets the "body" field.
func (m *ThoughtMutation) SetBody(s string) {
	m.body = &s
}

// Body returns the value of the "body" field in the mutation.
func (m *ThoughtMutation) Body() (r string, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the Thought entity.
// If the Thought object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ThoughtMutation) OldBody(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ResetBody resets all changes to the "body" field.
func (m *ThoughtMutation) ResetBody() {
	m.body = nil
}

// SetImageURL sets the "imageURL" field.
func (m *ThoughtMutation) SetImageURL(s string) {
	m.imageURL = &s
}

// ImageURL returns the value of the "imageURL" field in the mutation.
func (m *ThoughtMutation) ImageURL() (r string, exists bool) {
	v := m.imageURL
	if v == nil {
		return
	}
	return *v, true
}

// OldImageURL returns the old "imageURL" field's value of the Thought entity.
// If the Thought object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ThoughtMutation) OldImageURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldImageURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldImageURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImageURL: %w", err)
	}
	return oldValue.ImageURL, nil
}

// ResetImageURL resets all changes to the "imageURL" field.
func (m *ThoughtMutation) ResetImageURL() {
	m.imageURL = nil
}

// SetUserId sets the "userId" field.
func (m *ThoughtMutation) SetUserId(i int64) {
	m.userId = &i
	m.adduserId = nil
}

// UserId returns the value of the "userId" field in the mutation.
func (m *ThoughtMutation) UserId() (r int64, exists bool) {
	v := m.userId
	if v == nil {
		return
	}
	return *v, true
}

// OldUserId returns the old "userId" field's value of the Thought entity.
// If the Thought object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ThoughtMutation) OldUserId(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUserId is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUserId requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserId: %w", err)
	}
	return oldValue.UserId, nil
}

// AddUserId adds i to the "userId" field.
func (m *ThoughtMutation) AddUserId(i int64) {
	if m.adduserId != nil {
		*m.adduserId += i
	} else {
		m.adduserId = &i
	}
}

// AddedUserId returns the value that was added to the "userId" field in this mutation.
func (m *ThoughtMutation) AddedUserId() (r int64, exists bool) {
	v := m.adduserId
	if v == nil {
		return
	}
	return *v, true
}

// ResetUserId resets all changes to the "userId" field.
func (m *ThoughtMutation) ResetUserId() {
	m.userId = nil
	m.adduserId = nil
}

// Op returns the operation name.
func (m *ThoughtMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Thought).
func (m *ThoughtMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ThoughtMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.title != nil {
		fields = append(fields, thought.FieldTitle)
	}
	if m.body != nil {
		fields = append(fields, thought.FieldBody)
	}
	if m.imageURL != nil {
		fields = append(fields, thought.FieldImageURL)
	}
	if m.userId != nil {
		fields = append(fields, thought.FieldUserId)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ThoughtMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case thought.FieldTitle:
		return m.Title()
	case thought.FieldBody:
		return m.Body()
	case thought.FieldImageURL:
		return m.ImageURL()
	case thought.FieldUserId:
		return m.UserId()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ThoughtMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case thought.FieldTitle:
		return m.OldTitle(ctx)
	case thought.FieldBody:
		return m.OldBody(ctx)
	case thought.FieldImageURL:
		return m.OldImageURL(ctx)
	case thought.FieldUserId:
		return m.OldUserId(ctx)
	}
	return nil, fmt.Errorf("unknown Thought field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ThoughtMutation) SetField(name string, value ent.Value) error {
	switch name {
	case thought.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case thought.FieldBody:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case thought.FieldImageURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImageURL(v)
		return nil
	case thought.FieldUserId:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserId(v)
		return nil
	}
	return fmt.Errorf("unknown Thought field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ThoughtMutation) AddedFields() []string {
	var fields []string
	if m.adduserId != nil {
		fields = append(fields, thought.FieldUserId)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ThoughtMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case thought.FieldUserId:
		return m.AddedUserId()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ThoughtMutation) AddField(name string, value ent.Value) error {
	switch name {
	case thought.FieldUserId:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserId(v)
		return nil
	}
	return fmt.Errorf("unknown Thought numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ThoughtMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ThoughtMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ThoughtMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Thought nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ThoughtMutation) ResetField(name string) error {
	switch name {
	case thought.FieldTitle:
		m.ResetTitle()
		return nil
	case thought.FieldBody:
		m.ResetBody()
		return nil
	case thought.FieldImageURL:
		m.ResetImageURL()
		return nil
	case thought.FieldUserId:
		m.ResetUserId()
		return nil
	}
	return fmt.Errorf("unknown Thought field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ThoughtMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ThoughtMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ThoughtMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ThoughtMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ThoughtMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ThoughtMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ThoughtMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Thought unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ThoughtMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Thought edge %s", name)
}
