// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/d-exclaimation/fx-graphql-kit/ent/schema"
	"github.com/d-exclaimation/fx-graphql-kit/ent/thought"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	thoughtFields := schema.Thought{}.Fields()
	_ = thoughtFields
	// thoughtDescTitle is the schema descriptor for title field.
	thoughtDescTitle := thoughtFields[0].Descriptor()
	// thought.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	thought.TitleValidator = thoughtDescTitle.Validators[0].(func(string) error)
	// thoughtDescBody is the schema descriptor for body field.
	thoughtDescBody := thoughtFields[1].Descriptor()
	// thought.DefaultBody holds the default value on creation for the body field.
	thought.DefaultBody = thoughtDescBody.Default.(string)
	// thought.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	thought.BodyValidator = thoughtDescBody.Validators[0].(func(string) error)
}
