// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/d-exclaimation/fx-graphql-kit/ent/thought"
)

// ThoughtCreate is the builder for creating a Thought entity.
type ThoughtCreate struct {
	config
	mutation *ThoughtMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (tc *ThoughtCreate) SetTitle(s string) *ThoughtCreate {
	tc.mutation.SetTitle(s)
	return tc
}

// SetBody sets the "body" field.
func (tc *ThoughtCreate) SetBody(s string) *ThoughtCreate {
	tc.mutation.SetBody(s)
	return tc
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (tc *ThoughtCreate) SetNillableBody(s *string) *ThoughtCreate {
	if s != nil {
		tc.SetBody(*s)
	}
	return tc
}

// SetImageURL sets the "imageURL" field.
func (tc *ThoughtCreate) SetImageURL(s string) *ThoughtCreate {
	tc.mutation.SetImageURL(s)
	return tc
}

// SetUserId sets the "userId" field.
func (tc *ThoughtCreate) SetUserId(i int64) *ThoughtCreate {
	tc.mutation.SetUserId(i)
	return tc
}

// Mutation returns the ThoughtMutation object of the builder.
func (tc *ThoughtCreate) Mutation() *ThoughtMutation {
	return tc.mutation
}

// Save creates the Thought in the database.
func (tc *ThoughtCreate) Save(ctx context.Context) (*Thought, error) {
	var (
		err  error
		node *Thought
	)
	tc.defaults()
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ThoughtMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			node, err = tc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *ThoughtCreate) SaveX(ctx context.Context) *Thought {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (tc *ThoughtCreate) defaults() {
	if _, ok := tc.mutation.Body(); !ok {
		v := thought.DefaultBody
		tc.mutation.SetBody(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *ThoughtCreate) check() error {
	if _, ok := tc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New("ent: missing required field \"title\"")}
	}
	if v, ok := tc.mutation.Title(); ok {
		if err := thought.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf("ent: validator failed for field \"title\": %w", err)}
		}
	}
	if _, ok := tc.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New("ent: missing required field \"body\"")}
	}
	if v, ok := tc.mutation.Body(); ok {
		if err := thought.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf("ent: validator failed for field \"body\": %w", err)}
		}
	}
	if _, ok := tc.mutation.ImageURL(); !ok {
		return &ValidationError{Name: "imageURL", err: errors.New("ent: missing required field \"imageURL\"")}
	}
	if _, ok := tc.mutation.UserId(); !ok {
		return &ValidationError{Name: "userId", err: errors.New("ent: missing required field \"userId\"")}
	}
	return nil
}

func (tc *ThoughtCreate) sqlSave(ctx context.Context) (*Thought, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (tc *ThoughtCreate) createSpec() (*Thought, *sqlgraph.CreateSpec) {
	var (
		_node = &Thought{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: thought.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: thought.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: thought.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := tc.mutation.Body(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: thought.FieldBody,
		})
		_node.Body = value
	}
	if value, ok := tc.mutation.ImageURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: thought.FieldImageURL,
		})
		_node.ImageURL = value
	}
	if value, ok := tc.mutation.UserId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: thought.FieldUserId,
		})
		_node.UserId = value
	}
	return _node, _spec
}

// ThoughtCreateBulk is the builder for creating many Thought entities in bulk.
type ThoughtCreateBulk struct {
	config
	builders []*ThoughtCreate
}

// Save creates the Thought entities in the database.
func (tcb *ThoughtCreateBulk) Save(ctx context.Context) ([]*Thought, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Thought, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThoughtMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *ThoughtCreateBulk) SaveX(ctx context.Context) []*Thought {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
